"""Theme generation helpers for AI Learning Studio."""

from __future__ import annotations

import json
import os
from pathlib import Path
from shutil import rmtree

from core.errors import BuildError
from core.theme_models import (
    ThemeDesign,
    ThemeGenerationResult,
    ThemeRegistry,
    ThemeRegistryEntry,
)


THEME_REGISTRY_VERSION = 1
THEME_REGISTRY_FILENAME = "themes.json"


def build_theme_registry(theme_designs: list[ThemeDesign]) -> ThemeRegistry:
    if not theme_designs:
        raise BuildError("Generate theme assets", "no theme found")

    seen_ids: set[str] = set()
    active_themes: list[ThemeDesign] = []
    ordered_designs = sorted(theme_designs, key=lambda theme: theme.id)

    for theme in ordered_designs:
        if theme.id in seen_ids:
            raise BuildError(
                "Generate theme assets",
                f"duplicate theme ID: {theme.id}",
                path=theme.source_path,
                source_file=theme.source_path,
                theme_id=theme.id,
            )
        seen_ids.add(theme.id)
        if theme.status == "active":
            active_themes.append(theme)

    if not active_themes:
        raise BuildError("Generate theme assets", "no active theme exists")
    if len(active_themes) > 1:
        active_ids = ", ".join(theme.id for theme in active_themes)
        raise BuildError("Generate theme assets", f"multiple active themes exist: {active_ids}")

    public_entries = []
    for theme in ordered_designs:
        public_entries.append(
            ThemeRegistryEntry(
                id=theme.id,
                name=theme.name,
                description=theme.description,
                version=theme.version,
                status=theme.status,
                lang=theme.lang,
                manifest=f"themes/{theme.id}/manifest.json",
                tokens=f"themes/{theme.id}/tokens.json",
                style=f"themes/{theme.id}/style.css",
            )
        )

    return ThemeRegistry(
        version=THEME_REGISTRY_VERSION,
        active_theme=active_themes[0].id,
        themes=tuple(public_entries),
    )


def generate_theme_assets(theme_designs: list[ThemeDesign], staging_dir: Path) -> ThemeGenerationResult:
    registry = build_theme_registry(theme_designs)
    themes_root = staging_dir / "themes"
    if themes_root.exists():
        rmtree(themes_root)
    themes_root.mkdir(parents=True, exist_ok=True)

    ordered_designs = sorted(theme_designs, key=lambda theme: theme.id)
    generated_theme_files: list[str] = []
    repo_root = staging_dir.parent
    theme_source_files = [theme.source_path.relative_to(repo_root).as_posix() for theme in ordered_designs]
    total_theme_token_count = sum(theme.token_count() for theme in ordered_designs)

    themes_registry_path = themes_root / THEME_REGISTRY_FILENAME
    write_json(themes_registry_path, registry.to_public_dict(), sort_keys=False)
    generated_theme_files.append(f"dist/{themes_registry_path.relative_to(staging_dir).as_posix()}")

    for theme in ordered_designs:
        theme_dir = themes_root / theme.id
        theme_dir.mkdir(parents=True, exist_ok=True)

        tokens_path = theme_dir / "tokens.json"
        style_path = theme_dir / "style.css"
        manifest_path = theme_dir / "manifest.json"
        source_relative_path = theme.source_path.relative_to(repo_root).as_posix()

        write_json(tokens_path, theme.to_tokens_payload(), sort_keys=False)
        write_text(style_path, render_theme_stylesheet(theme, source_relative_path=source_relative_path))
        write_json(
            manifest_path,
            theme.to_manifest_payload(source_relative_path),
            sort_keys=False,
        )

        generated_theme_files.extend(
            [
                f"dist/{tokens_path.relative_to(staging_dir).as_posix()}",
                f"dist/{style_path.relative_to(staging_dir).as_posix()}",
                f"dist/{manifest_path.relative_to(staging_dir).as_posix()}",
            ]
        )

    generated_theme_files = sorted(generated_theme_files)
    return ThemeGenerationResult(
        registry=registry,
        discovered_theme_count=len(ordered_designs),
        active_theme_id=registry.active_theme,
        generated_theme_ids=tuple(theme.id for theme in ordered_designs),
        generated_theme_files=tuple(generated_theme_files),
        total_theme_token_count=total_theme_token_count,
        theme_source_files=tuple(theme_source_files),
        public_registry_output_file=f"dist/{themes_registry_path.relative_to(staging_dir).as_posix()}",
    )


def render_theme_stylesheet(theme_design: ThemeDesign, *, source_relative_path: str) -> str:
    lines = [
        "/*",
        f"Generated from {source_relative_path}.",
        "Do not edit this file directly.",
        "*/",
        "",
        ":root {",
    ]
    for token in theme_design.tokens():
        lines.append(f"  {token.css_variable}: {token.value};")
    lines.append("}")
    return "\n".join(lines)


def stylesheet_href_for_output(page_output_path: Path, stylesheet_path: Path) -> str:
    relative_path = os.path.relpath(stylesheet_path, start=page_output_path.parent)
    return Path(relative_path).as_posix()


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, payload: dict[str, object], *, sort_keys: bool) -> None:
    write_text(path, json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=sort_keys) + "\n")
